version: 0.2
env:
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    DOTNET_NOLOGO: "true"
    CONFIGURATION: "Release"

phases:
  install:
    runtime-versions:
      docker: 19
    
    commands:
      - dotnet-install.sh --jsonfile global.json
      - dotnet --info

  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - export image="$REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER"

      - dotnet restore
      - dotnet publish --no-restore
      - dotnet test --logger trx --no-build

      - |
        set -eo pipefail
        docker build -t $image .

        if [ "${CODEBUILD_WEBHOOK_TRIGGER:-branch/master}" = "branch/master" ]; then \
          docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER; \
          docker push $REPOSITORY_URI:nats2.1-$CODEBUILD_BUILD_NUMBER; \
        fi

reports:
  test-results:
    files:
      - "**/TestResults/*.trx"
    discard-paths: yes
    file-format: VisualStudioTrx
