version: 0.2

env:
  shell: bash
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY: "false"
    DOTNET_NOLOGO: "true"
    CONFIGURATION: "Release"

phases:
  install:
    runtime-versions:
      docker: 19

    commands:
      - dotnet-install.sh --jsonfile global.json
      - dotnet --info

  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
      - . ./scripts/codebuild-extras.sh

  build:
    commands:
      - export image=$REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - dotnet restore
      - dotnet publish --no-restore -p:DockerImageTag=$image
      - dotnet test --logger trx --no-build

      - ./scripts/create-config-files.sh $image

  post_build:
    commands:
      - ./scripts/package-template.sh
      - ./scripts/push-docker-images.sh

artifacts:
  discard-paths: yes
  files:
    - "bin/brighid-discord-adapter.template.yml"
    - "brighid-discord-adapter.*.config.json"

reports:
  test-results:
    files:
      - "**/TestResults/*.trx"
    discard-paths: yes
    file-format: VisualStudioTrx
