version: "3.4"
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  adapter: 
    image: mcr.microsoft.com/dotnet/sdk:5.0.401
    entrypoint: dotnet watch --project src/Adapter run
    working_dir: /app
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws
    environment:
      Environment: local
      CONFIGURATION: Debug
      Identity__IdentityServerUri: ${IDENTITY_SERVER_URI}
      Identity__ClientId: ${IDENTITY_CLIENT_ID}
      Identity__ClientSecret: ${IDENTITY_CLIENT_SECRET}
      Commands__ServiceUri: ${COMMANDS_SERVICE_URI}
      Commands__DefaultPrefix: '-'
      Database__Host: db
      Database__Name: ${DB_NAME}
      Database__User: ${DB_USER}
      Database__Password: ${DB_PASSWORD}
      Requests__QueueUrl: ${REQUESTS_QUEUE_URL}
      RestClient__RequestQueueUrl: ${REQUESTS_QUEUE_URL}
      Gateway__Uri: ${GATEWAY_URI}
      Adapter__Token: ${ADAPTER_TOKEN}
      Metrics__Namespace: ${METRICS_NAMESPACE}
      AWS_REGION: us-east-1
    labels:
      - traefik.enable=true
      - traefik.http.routers.adapter.rule=Host(`localhost`)
      - traefik.http.routers.adapter.entrypoints=web
      - traefik.http.services.adapter.loadbalancer.server.scheme=h2c

  db:
    image: mariadb/server:10.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
