version: "3.9"
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  adapter:
    image: brighid/discord-adapter
    working_dir: /app
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ./bin/Adapter/Debug/linux-musl-x64:/app
      - ~/.aws:/home/brighid/.aws
    environment:
      Environment: local
      CONFIGURATION: Debug
      Identity__IdentityServerUri: ${IDENTITY_SERVER_URI}
      Identity__ClientId: ${IDENTITY_CLIENT_ID}
      Identity__ClientSecret: ${IDENTITY_CLIENT_SECRET}
      Commands__ServiceUri: ${COMMANDS_SERVICE_URI}
      Commands__DefaultPrefix: '-'
      Database__Host: db
      Database__Name: ${DB_NAME}
      Database__User: ${DB_USER}
      Database__Password: ${DB_PASSWORD}
      Requests__QueueUrl: ${REQUESTS_QUEUE_URL}
      RestClient__RequestQueueUrl: ${REQUESTS_QUEUE_URL}
      Gateway__Uri: ${GATEWAY_URI}
      Auth__MetadataAddress: http://identity.dev.brigh.id/.well-known/openid-configuration
      Adapter__Token: ${ADAPTER_TOKEN}
      Adapter__RegistrationUrl: https://identity.dev.brigh.id/account/link/discord
      Metrics__Namespace: ${METRICS_NAMESPACE}
      AWS_REGION: us-east-1
    labels:
      - traefik.enable=true
      - traefik.http.routers.adapter.rule=Host(`localhost`)
      - traefik.http.routers.adapter.entrypoints=web
      - traefik.http.services.adapter.loadbalancer.server.scheme=h2c

  db:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - my-db:/var/lib/mysql

  envoy:
    image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.19.0.0-prod
    profiles:
      - prod

volumes:
  my-db: null
