Tags:
  Name: Brighid Discord Adapter
  Owner: Cythral
  Contact:Name: Talen Fisher
  Contact:Email: talen.fisher@cythral.com

Parameters:
  EnvironmentName:
    Development: dev
    Production: prod

  DomainName:
    Development: discord.dev.brigh.id
    Production: discord.brigh.id

  GatewayUri:
    Development: wss://gateway.discord.gg/?v=10&encoding=json
    Production: wss://gateway.discord.gg/?v=10&encoding=json

  AdapterToken:
    Development: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwF3IBfwfHUC5xJjj9LciUbsAAAAnTCBmgYJKoZIhvcNAQcGoIGMMIGJAgEAMIGDBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKkfYweUsr4WCtNlIgIBEIBWBij3YkYY8LidrA7tYv6f4cOFx7STWOOUQgg/N2KAh8Nrl35AyBLbyt8xx3LLeEDSG0jNuofavmdcnF+gd00ah8dlVAcNdKTp63X4AeM/49j/Fz6MPQ0=
    Production: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQH7c6I9/U8oOsaZnOZxwZXhAAAAnTCBmgYJKoZIhvcNAQcGoIGMMIGJAgEAMIGDBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKlVr9CIwyw+o0IQqgIBEIBWuCPGRVDCqewO1wSgOYqBRzWi/DsN+BICBxwshfADcw/KvrIlfQizoG3LSDLQ5/lmP/69EkTViLgjLUujdGyKJRgfSAEbw7W9+wQi7Iu3xWXC0G4gTBM=

  MetricsNamespace:
    Development: BrighidDiscordAdapter
    Production: BrighidDiscordAdapter

  IdentityServerUri:
    Development: identity.dev.brigh.id
    Production: identity.brigh.id

  StaticAssetsRepositoryUrl:
    Development: https://static.dev.brigh.id
    Production: https://static.brigh.id

  RegistrationUrl:
    Development: https://identity.dev.brigh.id/account/link/discord
    Production: https://identity.brigh.id/account/link/discord

  DatabaseHost:
    Development: db.dev.brigh.id
    Production: db.brigh.id

  DatabaseUser:
    Development: brighid-discord
    Production: brighid-discord

  DatabaseName:
    Development: brighid-discord
    Production: brighid-discord

  DatabasePassword:
    Development: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwFTov91m7LK3hkwJI3An32uAAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIxkKMyEvY/io7eRCAgEQgCw4hT/q4b4D40Gl4ajJ2pU9xaoZkvzTT/A3q/FNzxyeXRuAK4/u0gEu6BLkHA==
    Production: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQGYDlyJcWxnm2HX1OEFg3qrAAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFN8ERCNLIML21BezAgEQgCwiVhQ6CvdQJnvtv3MX0cBRvooKZLZs2T4za+67ujRvJdXEjXr8z2Jb4CV6Ag==

  ClientId:
    Development: "834067055162556446"
    Production: "671109403189182502"

  ClientSecret:
    Development: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwHA1fBeUj4VJAQk5BMUiffkAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzOoLZuffCjfk6TwgAgEQgDyvHCBOxfbT9nJxUJOas9LyEIhMQQXgnzzkAIS8oKU5oUwLLnCAgCXCPmFrIuy9kGtrlsjWkEqAO6zWva0=
    Production: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQFmlOkXvZ9HttJWb/gOompYAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVjJBeVtX6XQnCZQiAgEQgDxaWuYXuC0m3cf/+yahEDvuw7jobdPyW//bPqhaKYrjmX8EXxCnKtl9KymF8ljWBuGNhcEy3u5gkYuzsfg=

  CommandsServiceUri:
    Development: http://commands.dev.brigh.id
    Production: http://commands.brigh.id

  CommandsDefaultPrefix:
    Development: "-"
    Production: "."

  EnvoyImage:
    Development: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:arm64-v1.22.2.0-prod
    Production: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:arm64-v1.22.2.0-prod

  XrayImage:
    Development: public.ecr.aws/xray/aws-xray-daemon:3.3.3
    Production: public.ecr.aws/xray/aws-xray-daemon:3.3.3

  MeshNodeName:
    Development: discord-dev
    Production: discord-prod

  LogLevel:
    Development: Debug
    Production: Information

  ValidateScopes:
    Development: "true"
    Production: "false"

  DiscordWebhook:
    Development: AQICAHgxqyE01pRgdY0NFrCFnHs8QEnI57jBLR2eYgiKmodf3QGnj2ZhuMrJODJ7mkyH1pUNAAAA3DCB2QYJKoZIhvcNAQcGoIHLMIHIAgEAMIHCBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGP0Rz1wOupMAdSmmwIBEICBlOuaZXShCStGCsGgjPJj8zzA4b1AFzHGzRJCuhQ6sm752+3fMrypB1Dd6e5X0oq6+5nlJV6ZheIw++aI1oHVw5GfnwKiISHPSFofbk2EIbQZdkYo7q+ZBgy/UYcbgM6DjvThXbSVkyHybWn46WvD3GmEFSioajeiCX28XjoQ5c+1eGILQBrQNzOwiuNaOSjKojyK/F8=
    Production: AQICAHj+CJJyDJYWujPAHnzcoMKkQ147RXmTXzMNZV3u0Rf/xQE0EdwpxsI1X6FsQRvrFFDbAAAA3DCB2QYJKoZIhvcNAQcGoIHLMIHIAgEAMIHCBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFG3ZYLr7hKZuCTzjAIBEICBlBsO1w6uowVSODVaTDYYZ/wY5tXpFST+oZ3cxspFOKXdxrP+4Q+5oMxzDTR/CRjNmCNhCC876LwIjM7bZwTsgbSQssw2xrXn/401A1TIE/d9h0qXspUbff+eoDSh4/eKcKSyg3Pv3UCzjwbm3Ap+VyVL/T/pbsAdRyXI2JOModc0rVNzqkoKON8Oz79E5POaV0YV55w=
