Tags:
  Name: Brighid Discord Adapter
  Owner: Cythral
  Contact:Name: Talen Fisher
  Contact:Email: talen.fisher@cythral.com

Parameters:
  EnvironmentName:
    Dev: dev
    Prod: prod

  DomainName:
    Dev: discord.dev.brigh.id
    Prod: discord.brigh.id

  GatewayUri:
    Dev: wss://gateway.discord.gg/?v=8&encoding=json
    Prod: wss://gateway.discord.gg/?v=8&encoding=json

  AdapterToken:
    Dev: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwF3IBfwfHUC5xJjj9LciUbsAAAAnTCBmgYJKoZIhvcNAQcGoIGMMIGJAgEAMIGDBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKkfYweUsr4WCtNlIgIBEIBWBij3YkYY8LidrA7tYv6f4cOFx7STWOOUQgg/N2KAh8Nrl35AyBLbyt8xx3LLeEDSG0jNuofavmdcnF+gd00ah8dlVAcNdKTp63X4AeM/49j/Fz6MPQ0=
    Prod: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQH7c6I9/U8oOsaZnOZxwZXhAAAAnTCBmgYJKoZIhvcNAQcGoIGMMIGJAgEAMIGDBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKlVr9CIwyw+o0IQqgIBEIBWuCPGRVDCqewO1wSgOYqBRzWi/DsN+BICBxwshfADcw/KvrIlfQizoG3LSDLQ5/lmP/69EkTViLgjLUujdGyKJRgfSAEbw7W9+wQi7Iu3xWXC0G4gTBM=

  MetricsNamespace:
    Dev: BrighidDiscordAdapter
    Prod: BrighidDiscordAdapter

  IdentityServerUri:
    Dev: identity.dev.brigh.id
    Prod: identity.brigh.id

  StaticAssetsRepositoryUrl:
    Dev: https://static.dev.brigh.id
    Prod: https://static.brigh.id

  RegistrationUrl:
    Dev: https://identity.dev.brigh.id/account/link/discord
    Prod: https://identity.brigh.id/account/link/discord

  DatabaseHost:
    Dev: db.dev.brigh.id
    Prod: db.brigh.id

  DatabaseUser:
    Dev: brighid-discord
    Prod: brighid-discord

  DatabaseName:
    Dev: brighid-discord
    Prod: brighid-discord

  DatabasePassword:
    Dev: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwFTov91m7LK3hkwJI3An32uAAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIxkKMyEvY/io7eRCAgEQgCw4hT/q4b4D40Gl4ajJ2pU9xaoZkvzTT/A3q/FNzxyeXRuAK4/u0gEu6BLkHA==
    Prod: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQGYDlyJcWxnm2HX1OEFg3qrAAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFN8ERCNLIML21BezAgEQgCwiVhQ6CvdQJnvtv3MX0cBRvooKZLZs2T4za+67ujRvJdXEjXr8z2Jb4CV6Ag==

  ClientId:
    Dev: "834067055162556446"
    Prod: "671109403189182502"

  ClientSecret:
    Dev: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwHA1fBeUj4VJAQk5BMUiffkAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzOoLZuffCjfk6TwgAgEQgDyvHCBOxfbT9nJxUJOas9LyEIhMQQXgnzzkAIS8oKU5oUwLLnCAgCXCPmFrIuy9kGtrlsjWkEqAO6zWva0=
    Prod: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQFmlOkXvZ9HttJWb/gOompYAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVjJBeVtX6XQnCZQiAgEQgDxaWuYXuC0m3cf/+yahEDvuw7jobdPyW//bPqhaKYrjmX8EXxCnKtl9KymF8ljWBuGNhcEy3u5gkYuzsfg=

  CommandsServiceUri:
    Dev: http://commands.dev.brigh.id
    Prod: http://commands.brigh.id

  CommandsDefaultPrefix:
    Dev: "-"
    Prod: "."

  EnvoyImage:
    Dev: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.19.1.1-prod
    Prod: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.19.1.1-prod

  MeshNodeName:
    Dev: discord-dev
    Prod: discord-prod
