version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - docker pull $REPOSITORY_URI:$OLD_TAG
      - docker tag $REPOSITORY_URI:$OLD_TAG $REPOSITORY_URI:$NEW_TAG
      - docker push $REPOSITORY_URI:$NEW_TAG
